## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  # Issues created to resolve this: https://github.com/mojaloop/project/issues/3260
  "@mojaloop/central-services-shared",
  "joi"  # The latest hapi-swagger (17.3.2) still requires joi@17.x - there's no version supporting joi 18.
]
